apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:DaEXYe+hMfLTAw==,iv:m19tJJYDQ0b1mue4MUS2cgXHQiw+sGTtdyJv/7XmUeA=,tag:/S2wcSo4oOfnZxMVpwLyeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e5wxxyrzdjmtjwhc7lmslf7cs8lfp4rly6dwhz07lx9pppn0xv4sk2q4d2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6NFZmMmRCOHV3WGF6OFcv
            bm5jdUhCUDI1dmdnZkV1TzZpV3dFMkhKeHlZCllqWllTcVIrUi9janhxUHVmd2VQ
            cm13eGV6eG01V3NsQTFsdkRHYlRqaGcKLS0tIFI3dWxnMWw5TGk1cURFWUdWM0Yy
            NTN2OXRWRzRjRUUzVEdiTUJ3OXpDR2cKDj/2XVbvcSzzwNm8/475QsTftbp0wIbf
            SI76lQU4iNFBqHpsMYT95Y/Cq8PMKPjxo+Kc763xSMt+W7Tz3SX2WQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-19T19:37:06Z"
    mac: ENC[AES256_GCM,data:2BEKHAMlhw2xZc6q5qdREFI41xnqQlrXWPnL+Nbcysavm4FTenpAlfxDb0P5+OQ5kqG6YvNU+6XzJ/eqkG14kyP9Z+PlOUt6ANKONvXYyZatXxWdHgRyuv8SmhEW2irdod6/KP7pfNtItZLj/sfjFAQa6j6hPlmenuzu24zQfzo=,iv:CD4vnoVwH1Y29dpQiiJe33qUSC/BjSiIZbyV93UzzNo=,tag:UhwelQGK8n3j4wLj+stl/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
