---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Los_Angeles"
  KUBE_VIP_ADDR: "10.0.22.22"
  METALLB_LB_RANGE: "10.0.22.221-10.0.22.225"
  METALLB_K8S_GATEWAY_ADDR: "10.0.22.221"
  METALLB_INGRESS_ADDR: "10.0.22.222"
